# Generated by Django 5.0.2 on 2024-02-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/customImages')),
            ],
        ),
        migrations.CreateModel(
            name='Classmates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('profile_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schoolGrade.images')),
            ],
        ),
    ]
