# Generated by Django 5.0.2 on 2024-02-26 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolGrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmates',
            name='profile_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolGrade.images'),
        ),
    ]
