# Generated by Django 5.0.2 on 2024-02-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolGrade', '0003_images_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='desc',
            field=models.CharField(default='2024-02-26 19:48:41.302312', max_length=128),
        ),
    ]
