# Generated by Django 5.0.2 on 2024-02-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolGrade', '0004_alter_images_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='desc',
            field=models.CharField(default='2024-02-26 21:02:17.011874', max_length=128),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='customImages'),
        ),
    ]
