# Generated by Django 5.0.2 on 2024-02-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolGrade', '0005_alter_images_desc_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='desc',
            field=models.CharField(default='2024-02-26 21:02:20.940996', max_length=128),
        ),
    ]
