# Generated by Django 5.0.2 on 2024-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolGrade', '0007_alter_images_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='desc',
            field=models.CharField(max_length=128),
        ),
    ]
