# Generated by Django 5.0.2 on 2024-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolGrade', '0008_alter_images_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='desc',
            field=models.CharField(default='.', max_length=128),
        ),
    ]
